---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cron-ical.discord.jp
  resources:
  - cronicalfeeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cron-ical.discord.jp
  resources:
  - cronicalfeeds/finalizers
  verbs:
  - update
- apiGroups:
  - cron-ical.discord.jp
  resources:
  - cronicalfeeds/status
  verbs:
  - get
  - patch
  - update
